export const MERCHANT_QUOTES = [
	"People always want magic weapons. Just get a stick. Cheaper, and you can hit 'em from a distance.",
	"Elves live forever but you never see ‘em doin’ anything with it. Just sort of standin’ about, lookin’ smug.",
	"What you need a shield for? Just don’t get in fights, that’s what I do.",
	"You want a map? Here’s a thought—try just remembering stuff.",
	"People say goblins are evil. They’re probably just bored, wandering around caves all day.",
	"People bang on about ‘the hero’s journey.’ I’d rather stay in, if I’m honest.",
	"Elves act like they’re special ‘cause they live longer. Well, a turtle lives ages too, but no one’s impressed by that.",
	"Orcs are just misunderstood. They’re not all bad. Some of them are just... misunderstood.",
	"I just wrap any old shit up and give it. You like this tenor. Rip you off. Because I'm busy. And that's what happens in this country.",
	"Buy it if you want, I'm not fussed. Right? Shop around... Come back... It's up to you. I'm not pushing you into anything, right?",
	"People want armor. Why don’t they just try not getting hit? Seems easier.",
	"You know what’s underrated? Staying put. No one ever gets lost just sittin’ at home.",
	"You ever notice the 'heroes' do all the damage? Monsters are just defending their homes, aren’t they?",
	"You want armor? Just wear a thick jumper. Lot more comfortable, innit?",
	"A ‘quest for glory’? It’s walking in mud and nearly dying every five minutes. I’ll pass.",
	"Everyone wants to save the kingdom. Have you looked around? It’s a dump!",
	"Armor, potions, spells—you need all this ‘cause you keep poking things you shouldn’t. Try not doing that.",
	"Dragons, goblins, ‘ancient evils’... it’s all the same rubbish, just another thing to whinge about.",
	"Another ‘hero’… great. They all come in, buy stuff, then go right off and get themselves killed. Pointless, really.",
	"People goin’ on quests… I’d just get lost. Probably end up right back here anyway.",
];

export const POTION_SELLER_QUOTES = [
	"I don’t just sell potions, mate. I sell results. You’ll be thanking me later.",
	"It’s not magic, it’s science... with a dash of mystery. But mostly science, really.",
	"I’m not just a potion seller, I’m a healer... and a businessman. Big difference.",
	"I’m not saying I’m a genius, but when you need potions, you do come to me, don’t you?",
	"I could charge more, but I’m a man of the people. You’re welcome, by the way.",
	"I mean, I don’t have to explain how potions work. You drink, you feel better. That’s it.",
	"There’s potions, and then there’s potions. Mine are the good kind. Trust me.",
	"People think it's all about magic, but it’s about quality. And I’ve got quality.",
	"Not to brag, but if potions were a sport, I’d be... well, I’d be at the top, probably.",
	"I don’t need to advertise. My potions speak for themselves. Well, they would if they could.",
	"It’s not just about selling potions. It’s about selling the future. That’s what I do.",
	"Why settle for anything less when you can have the ultimate potion experience? With me.",
	"My potions don’t just heal, they transform. They change lives... and moods.",
	"I’m not just a potion seller. I’m a friend. A friend who sells potions.",
	"They say money can’t buy happiness, but it can buy my potions. Same thing, really.",
	"I’m not just a potion seller. I’m a lifestyle choice. A very good lifestyle choice.",
	"People want magic. I give them the next best thing: my potions, which are basically magic.",
	"People ask me, ‘How do you make potions?’ I say, ‘It’s just common sense, really.'",
	"Look, if you want the best, you come to me. It’s not rocket science. It’s potion science.",
	"I could sell you potions all day. And I do. That’s why I’m the best at it, really.",
];
